---
title: "Instructions for *ACL Proceedings"
authors:
  - name: Name1 Surname
    equal-contributor: true
    affiliations:
      - ref: cmu
      - ref: chicago
  - name: Name2
    corresponding: true
    email: "xx@edu.com"
    affiliations:
      - ref: cmu
      - ref: chicago
  - name: Name3
    equal-contributor: true
    affiliations:
      - ref: chicago
affiliations:
  - id: cmu
    department: Department of computer science
    name: Carnegie Mellon University
    city: Shenzhen
    country: China
  - id: chicago
    name: University of Chicago
    city: Chicago
abstract: |
  This document is a supplement to the general instructions for *ACL authors. It contains instructions for using the \LaTeX{} style files for ACL conferences.
  The document itself conforms to its own specifications, and is therefore an example of what your manuscript should look like.
  These instructions should be used both for papers submitted for review and for final versions of accepted papers.
keywords:
  - Machine Learning
  - ICML
bibliography: custom.bib
format: 
  acl-pdf:
    accepted: false
---


# Introduction

These instructions are for authors submitting papers to \*ACL conferences using \LaTeX. They are not self-contained. All authors must follow the general instructions for \*ACL proceedings [^1], and this document contains additional instructions for the \LaTeX{} style files.

The templates include the \LaTeX{} source of this document (`acl_latex.tex`), the \LaTeX{} style file used to format it (`acl.sty`),
an ACL bibliography style (`acl_natbib.bst`),
an example bibliography (`custom.bib`),
and the bibliography for the ACL Anthology (`anthology.bib`).

[^1]: [http://acl-org.github.io/ACLPUB/formatting.html](http://acl-org.github.io/ACLPUB/formatting.html)

# Engines

To produce a PDF file, pdf\LaTeX{} is strongly recommended (over original \LaTeX{} plus dvips+ps2pdf or dvipdf). Xe\LaTeX{} also produces PDF files, and is especially suitable for text in non-Latin scripts.

You can use the command \verb|\citealp| (alternative cite without parentheses) to get ``author, year'' citations, which is useful for using citations within parentheses [e.g. @Gusfield:97]

::: {#refs}

:::

\appendix

# Example Appendix

This is an appendix.

